version: '3.8'

services:
  train-service:
    build:
      context: ../.
      dockerfile: train_pipeline/train_image.Dockerfile
    volumes:
      - ../src:/app/src
      - ../conf:/app/conf
      - ../logs:/app/logs
      - ../pytorch_models:/app/pytorch_models
      - ../datasets:/app/datasets
    environment:
      PYTHONPATH: "/app"
    command: ["python", "src/train.py"]
